version: "2"
linters:
  enable:
    - bodyclose
    - errorlint
    - goprintffuncname
    - misspell
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - usestdlibvars
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/simplesurance/dependencies-tool
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
