---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        go: ["1.22"]
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: build
        run: "go build ./..."

  test:
    strategy:
      matrix:
        go: ["1.22"]
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: test
        run: go test -race ./...

  golangci:
    strategy:
      matrix:
        go: ["1.22"]
        lint: ["v1.56"]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ matrix.lint }}
